config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :items
  get "/my_items", to: "items#user_index"
  get "/user_page", to: "items#user_page"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :phone_number, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :phone_number, :first_name, :last_name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
    if params[:query].present?
      sql_subquery = <<~SQL
        items.name @@ :query
        OR items.description @@ :query
        OR items.brand @@ :query
      SQL
      @items = @items.where(sql_subquery, query: params[:query])
    end
  end

  def show
  end

  def user_index
    @items = Item.all
    @items = @items.where(user_id: current_user)
  end

  def user_page
    @items = Item.all
    @user = User.find(params[:format])
    @items = @items.where(user_id: @user)

  end

  def new
    @item = Item.new
  end

  def destroy
    @item.destroy
    redirect_to my_items_path, status: :see_other
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :brand, :weight, :size, :year, :description, :price, :photo )
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-preview.redd.it/lS15HBEbnBjBnAHpKJ2-CrMylW1sNSA0KJ7gDcg5ADk.jpg?auto=webp&s=1754f6602a1bf91485fdedb2b7c5c5708b38e10b);">
  <div class="container">
    <h1>Fish anywhere!</h1>
    <p>Change your life, learn to fish.</p>
    <div class="row justify-content-left">
      <div class="col-sm-4 my-3">
        <%= form_with url: items_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for: Name, Category, Location"
          %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row row-cols-1 row-cols-md-3">
  <% @items.each do |item| %>
    <div class="col">
      <div class="card" style="width: 18rem; ">
        <%= link_to item_path(item), style:"text-decoration: none; color: black" do %>
          <img style="height: 150px; object-fit: cover; object-position: center" class="card-img-top" src="<%= cl_image_path item.photo.key %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= item.name %></h5>
            <p class="card-text"><%= item.description %></p>
          </div>
        <% end %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= item.brand %></li>
          <li class="list-group-item"><span>Size: </span><%= item.size %> Meters</li>
          <li class="list-group-item"><span>Price: </span><%= item.price %>€/K</li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-preview.redd.it/lS15HBEbnBjBnAHpKJ2-CrMylW1sNSA0KJ7gDcg5ADk.jpg?auto=webp&s=1754f6602a1bf91485fdedb2b7c5c5708b38e10b);">
  <div class="container">
    <h1>Fish anywhere!</h1>
    <p>Change your life, learn to fish.</p>
  </div>
</div>

<div>
  <%= simple_form_for [@item] do |f| %>
    <%= f.input :name %>
    <%= f.input :brand %>
    <%= f.input :weight %>
    <%= f.input :size %>
    <%= f.input :year %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <br>
  <%= f.submit class: "btn btn-reserve" %>
  <% end %>
  <%= link_to 'Cancel', items_path, class: "btn btn-reserve1" %>
</div>

app/views/items/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-preview.redd.it/lS15HBEbnBjBnAHpKJ2-CrMylW1sNSA0KJ7gDcg5ADk.jpg?auto=webp&s=1754f6602a1bf91485fdedb2b7c5c5708b38e10b);">
  <div class="container">
    <h1>Fish anywhere!</h1>
    <p>Change your life, learn to fish.</p>
  </div>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card" style="width: 18rem; ">
      <img style="height: 150px; object-fit: cover; object-position: center" class="card-img-top" src="<%= cl_image_path @item.photo.key %>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= @item.name %></h5>
        <p class="card-text"><%= @item.description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @item.brand %></li>
        <li class="list-group-item"><%= @item.updated_at %></li>
        <li class="list-group-item"><span>Price: </span><%= @item.price %>€/K</li>
        <%= link_to user_page_path(@item.user) do%>
          <li class="list-group-item"><span><%= @item.user.first_name %> <%= @item.user.last_name %></span></li>
        <% end %>
      </ul>
      <div class="card-body">
        <%= link_to "https://wa.me/+351#{@item.user.phone_number}/?text=Ola", class: "item-card-button" do %>
          <%= image_tag("whatsapp.svg", width: 25) %> Contactar
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/user_index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-preview.redd.it/lS15HBEbnBjBnAHpKJ2-CrMylW1sNSA0KJ7gDcg5ADk.jpg?auto=webp&s=1754f6602a1bf91485fdedb2b7c5c5708b38e10b);">
  <div class="container">
    <h1>Fish anywhere!</h1>
    <p>Change your life, learn to fish.</p>
  </div>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @items.each do |item| %>
  <div class="col">
    <div class="card" style="width: 18rem; ">
      <img style="height: 150px; object-fit: cover; object-position: center" class="card-img-top" src="<%= cl_image_path item.photo.key %>" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= item.name %></h5>
        <p class="card-text"><%= item.description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= item.brand %></li>
        <li class="list-group-item"><span>Size: </span><%= item.updated_at %> Meters</li>
        <li class="list-group-item"><span>Price: </span><%= item.price %>€/K</li>
      </ul>
      <div class="card-body">
        <a href="#" class="card-link">Editar</a>
        <%= link_to "Remover", item_path(item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/items/user_page.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-preview.redd.it/lS15HBEbnBjBnAHpKJ2-CrMylW1sNSA0KJ7gDcg5ADk.jpg?auto=webp&s=1754f6602a1bf91485fdedb2b7c5c5708b38e10b);">
  <div class="container">
    <h1><%= @user.first_name %> <%= @user.last_name %></h1>
    <p></p>
    <div class="row justify-content-left">
      <div class="col-sm-4 my-3">

      </div>
    </div>
  </div>
  <%= cl_image_tag @user.photo.key, class: "page-avatar" %>
</div>

<div class="row row-cols-1 row-cols-md-3">
  <% @items.each do |item| %>

      <div class="col">
        <div class="card" style="width: 18rem; ">
           <%= link_to item_path(item), style:"text-decoration: none; color: black" do %>
          <img style="height: 150px; object-fit: cover; object-position: center" class="card-img-top" src="<%= cl_image_path item.photo.key %>" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><%= item.name %></h5>
              <p class="card-text"><%= item.description %></p>
            </div>
          <% end %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= item.brand %></li>
            <li class="list-group-item"><span>Size: </span><%= item.size %> Meters</li>
            <li class="list-group-item"><span>Price: </span><%= item.price %>€/K</li>
          </ul>
        </div>
      </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishBay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-preview.redd.it/lS15HBEbnBjBnAHpKJ2-CrMylW1sNSA0KJ7gDcg5ADk.jpg?auto=webp&s=1754f6602a1bf91485fdedb2b7c5c5708b38e10b);">
  <div class="container">
    <h1>Fish khau bla bla</h1>
    <p>Change your life, learn to fish.</p>
    <div class="row justify-content-left">
      <div class="col-sm-4 my-3">
        <%= form_with url: items_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for: Name, Category, Location"
          %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://t4.ftcdn.net/jpg/04/07/38/35/240_F_407383528_WUNdGkUmB9D27IFGJSZQqf7V1t3KxCyJ.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Anunciar", new_item_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag "avatar.jpg", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "O meu perfil", "#", class: "dropdown-item" %>
              <%= link_to "Os meus Anúncios", my_items_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>